### ISSUE TITLE
Docker Nanomq Slim doesn't buffer to SQLite upon connection disconnect and doesn't resend them

### ISSUE THREAD

**Issue by charlesjIV** [nanomq/nanomq#1476]
**Describe the bug**
Based on the documentation, it seems as though if I just add a "sqlite" section to my .conf file, MQTT messages should be buffered into a database when the connection to a bridged broker is severed. Using Windows Desktop Docker, NanoMQ 0.19.5 Slim, when the connection between the "broker.emqx.io:1883" is disconnected, messages sent to Nano are not stored in SQLite and re-sent upon reconnect. 

**Expected behavior**
Based on documentation, it seems as though, when the connection is severed, messages should be buffered in SQLite until the connection is restored, then sent to the EMQX broker. 

**Actual Behavior**
Logs show that the connection has been disconnected/reconnected, SQLite DB is created, but nothing is sent after reconnect. 

**To Reproduce**
Use Windows Docker Desktop, NanoMQ Slim, Version 0.19.5, Disabled Network adapter to cause a disconnect between default broker, and used the attached ".conf" file. 

** Environment Details **
 - NanoMQ version: NanoMQ version 0.19.5 Slim
 - Windows 11/Docker Desktop
 - Disabled Network adapter

**Additional context**
Attempted to test on NanoMQ full as well and had the same thing happen. I was able to use the Rule engine on the full version to log all messages to the SQLite DB. 

[nanomq.txt](https://github.com/emqx/nanomq/files/12838006/nanomq.txt)

**Comment by RanMaoyi** [comment]
Hello,
First, please use nanomq-0.20.0-linux-amd64-sqlite.deb instead of the slim version.
Upon checking your configuration file, I noticed that you are using the sqlite node, which is not suitable for your needs. Please use the bridges.mqtt.cache node instead. This change will resolve the issue you are facing.

For example:
<img width="1013" alt="image" src="https://github.com/emqx/nanomq/assets/16575896/d5f84d30-5fa1-4ae9-9b52-ee1beb06515d">
