### ISSUE TITLE
Nanomq refuses any subsequent requests after two clients connect with the same client id

### ISSUE THREAD

**Issue by MukalDadhwal** [nanomq/nanomq#1945]
**Describe the bug**
I have been testing nanomq from a week and have managed to setup a correct config to solve my usecase. But apparently while testing when two people connect with the same client id it disconnects the previous and refuses the new one which is an expected behavior given in the mqtt specification and also referenced in #1927. But after that all the subsequent requests are blocked which are made with any mechanism like username/passwd or different clientid. 

**Expected behavior**
The expected behavior should be that after disconnecting the clients the sessions should resume normally

**To Reproduce**
running latest docker image [link](https://hub.docker.com/layers/emqx/nanomq/latest-full/images/sha256-c967ee4bf2d390a6ae9796b7652dc19b682a19345fe700be2a5274ba29241c17?context=explore)

**Environment Details**
 - NanoMQ version: latest 0.23.0
 - Ubuntu 22.04.5 LTS
 - tested using Dart & MQTT explorer
 
**Client SDK**
test cases written with dart

**Additional context**
no appreciable logs were produced while this was tested
[reproduce.zip](https://github.com/user-attachments/files/17892606/reproduce.zip)

**Comment by JaylinYu** [comment]
#1927 is only with a false released ver of 0.22.8, and it has been fixed by re-releasing a correct ver again to overwrite it. Plz try the updated binary installed ver to avoid #1927.

I just tested with `docker run -d --name nanomq -p 1883:1883 -p 8083:8083 -p 8883:8883 emqx/nanomq:latest`, works fine, Only see client keeps kicking each other, no hang. 

And I see you configured HTTP Auth in your config file, and there is `timeout` logged in your attachment, plz also be awared that, HTTP Auth plugin is not async yet, it consumes a Actor task thread to fire HTTP request and wait for the response, if all threads are wating for HTTP response, then there is no other thread to take up remaining works, this is similiar to what you called "refuse all requests".

**Comment by JaylinYu** [comment]
You can disable all your HTTP Auth and ACL to see the difference.

BTW set log level to info for more detailed log.

**Comment by JaylinYu** [comment]
I TRIED my own HTTP Server. Works fine. You are definitely blocking all thread at sending http  request. Will try to make this async, But not as an urgent feature.
