### ISSUE TITLE
Improper Handling of Payload Length

### ISSUE THREAD

**Issue by keymandll** [nanomq/nanomq#203]
When the MQTT packet length is tampered with and is lower than expected, a `memcpy` [1] operation receives a `size` value that makes the source buffer location points to or into an unallocated memory area. As a result, nanomq crashes.

The below `connect` message can be used to reproduce the issue.

```
"\x10\x07\x00\x04\x4d\x51\x54\x54\x04\xc2\x00\x3c\x00\x0b\x74\x65" +\
"\x73\x74\x2d\x70\x79\x74\x68\x6f\x6e\x00\x05\x61\x64\x6d\x69\x6e" +\
"\x00\x08\x70\x61\x73\x73\x77\x6f\x72\x64"
```

As a result of the above message, `memcpy` receives a very large positive number (0xfffffffc in case of this proof of concept) as the `size` argument.

The problem seems to be with how the payload length is calculated [2]. Suspected that the unusual packet length `msg_len` is a smaller value than `used_pos`, therefore the subtraction results in a negative number. However, `memcpy` expects the size as `size_t`, which is *unsigned*. Therefore, due to the "casting" of a negative number to `size_t` the length becomes a very large positive number (0xfffffffc in case of this proof of concept).

[1] https://github.com/nanomq/nanomq/blob/10fcd9ccb81a9aca1dc089131e850930eda9466e/nanomq/pub_handler.c#L964
[2] https://github.com/nanomq/nanomq/blob/10fcd9ccb81a9aca1dc089131e850930eda9466e/nanomq/pub_handler.c#L956

**Comment by JaylinYu** [comment]
Hi Zsolt, thank you for your detailed explaination!

**Comment by JaylinYu** [comment]
We should not allow such a malformed CONNECT packet to penetrate the transport layer. I have pushed a pr for band-aid fix, could you check that for me?
 However, I believe there are more security bugs uncovered.

**Comment by JaylinYu** [comment]
I found that the false news is back online https://www.itpro.com/network-internet/internet-of-things-iot/361010/100-million-iot-devices-affected-by-zero-day-flaw 

The following comments is for those people come from the news link. 

It’s an untrue story where the description and exaggeration of how EMQ negatively impacted the real-world and how Guardara saved everything were all incorrect.

The project of which Guardara uncovered a vulnerability is NanoMQ,  As the maintainer of NanoMQ project, I am fully aware of how security matters and the range this bug affected. NanoMQ is a very new open-source project which hasn’t hit General Availability(NO 100M Devices) and is seldom adopted by any customers/users/companies in the production environment yet. For an open-source project in a very initial, immature, and evolving stage, a vulnerability is not uncommon and doesn’t have such severe impact as Guardara described.

EMQ as a company that holds long-term commitments to open-source is keeping creating and providing creative new open-source projects to contribute to the IoT world, most of our open-source projects are even not commercialized (like NanoMQ in this scenario).

It’s sad and disappointing for us to see Guardara told such an exaggerated and untrue story for its branding purpose, and we’ve reserved every right of a lawsuit against it. But before that, in order to deliver correct information to the world, we sincerely seek your kind understanding and support to unpublish this press release first. 

Additionally, EMQ has invested hugely in global IoT security in the following year, sponsor HONGKONG polytechnic university for ITF funds in a security project. we appreciate the efforts of all security researchers, there are a lot of valuable papers are taking NanoMQ as a research target and achieve significant outcome.
