### ISSUE TITLE
no ctx found! (There is no enough logic threads)

### ISSUE THREAD

**Issue by topdayday** [nanomq/nanomq#996]
**Describe the bug**
version 0.14.8
ERROR /home/runner/work/nanomq/nanomq/nng/src/sp/protocol/mqtt/nmq_mqtt.c:1066: no ctx found!! create more ctxs!

日志报了这个错后，部分客户端就无法连接了。

**Comment by JaylinYu** [comment]
The Broker is complaining about not having enough logic thread for your scenario. Perhaps there are too many operations are blocked due to client-side issues. Please increase the number of "parallel" in nanomq.conf. 

这是因为服务发现没有足够的逻辑现成来处理客户端请求。这可能是由于客户端有许多阻塞的操作，亦或者只是context的数量不够了。请增大 配置文件中 "parallel" 数量的。例如设置成1024。但是这条log只是说明处理收到消息的context不够，影响如Sub一类的操作，而新客户端连接是在传输层完成的，不应受到影响。
